import type { Metadata } from "next";
import "../../public/styles/main.css"
import "../../public/styles/style.css"
import { AuthProvider } from "@/context/auth";
import Script from 'next/script'

export const metadata: Metadata = {
  title: "StudyCompanion  | Find study companions around the world!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
            <AuthProvider>
                {children}
            </AuthProvider>
            <Script src="/js/script.js"></Script>
        </body>
    </html>
  );
}
